# Only di-nails.tanem.ru. HTTPS is enabled after this vhost using Certbot.
server {
    listen 80;
    listen [::]:80;
    server_name di-nails.tanem.ru;
    root /var/www/di-nails;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
